name: nats-base-client

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [master]

jobs:
  build:
    name: ${{ matrix.config.kind }} ${{ matrix.config.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.0.5]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Lint Deno Module
        run: deno fmt --check

      - name: bundle
        run: deno bundle --unstable src/nats.ts nats.js

      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          startsWith(github.ref, 'refs/tags/') &&
          !startsWith(github.ref, 'refs/tags/std/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            src/*.ts
          draft: true
